sudo: required
services:
  - docker

env:
  - CI="true"

before_install:
  - docker build -t soufianead/docker-p1 -f Dockerfile.dev .

script:
  - docker run soufianead/docker-p1 npm run test -- --coverage
